### ISSUE TITLE
Installer broken

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/joomla-es6#115]
### Steps to reproduce the issue
- Pull from master branch
- Try to install joomla-es6 repo

### Expected result
- Installer should appear

### Actual result
![image](https://user-images.githubusercontent.com/13379595/38193913-2af2f40e-3692-11e8-9d88-bf5bbf12fa92.png)

- Installer is not working

### System information (as much as possible)
= PHP7, Windows, Chrome 63

**Comment by kasvith** [comment]
Working fine in `joomla-cms` repo `4.0-dev`
So it might be a problem in here

**Comment by dneukirchen** [comment]
This is related to @dgt41 changes in #35 

For now: rename media/system/core.js to media/system/core.min.js

**Comment by kasvith** [comment]
Done but cant install it 
![image](https://user-images.githubusercontent.com/13379595/38195599-e4a87244-369b-11e8-900a-1f5cf46d838d.png)
