### ISSUE TITLE
Auto generate ALL the calendar files

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/joomla-es6#37]
### Steps to reproduce the issue

Enhance https://github.com/joomla/joomla-cms/blob/4.0-dev/build/build-modules-js/installation.js to also auto generate the calendar locales.

I opened this issue so nobody tries to convert those to ES6, by the way they are already ES6!

**Comment by dneukirchen** [comment]
https://github.com/joomla/joomla-cms/pull/19772
