### ISSUE TITLE
Scrap localStorageEnabled

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/joomla-es6#39]
### Steps to reproduce the issue

It's used only in one file and it's not belong to Joomla's API

<img width="550" alt="screen shot 2018-02-21 at 11 58 32" src="https://user-images.githubusercontent.com/3889375/36476611-b2d5ad48-16fe-11e8-8124-7589e93506ed.png">

So whoever does the admin-menu.js needs to include this function there as it's gonna be removed from core.js

**Comment by C-Lodder** [comment]
I was forced to add that by George -_-

...incase some people have localstorage disabled

**Comment by dgrammatiko** [comment]
The code is fine but it should not be part of the joomla's API
