### ISSUE TITLE
Problem in com_content in this Repo

### ISSUE THREAD

**Issue by astridx** [joomla-projects/joomla-es6#46]
### Steps to reproduce the issue

1. Install this repo without sample data and not multilingual
2. Create an article with the tile "test" and the content "test".

### Expected result
Article is saved

### Actual result
You get an SQL error.
![articles new test administration](https://user-images.githubusercontent.com/9974686/36506046-b87d5b5e-1755-11e8-8737-c72c0a35bc86.png)

### System information (as much as possible)

No debug mode

PHP Built On | Linux acer 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
-- | --
Database Version | 5.7.21-0ubuntu0.16.04.1
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.22-0ubuntu0.16.04.1
Web Server | Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 19-November-2017 16:34 GMT
User Agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by anuragteapot** [comment]
Can't confirm

![screenshot from 2018-02-22 03-04-36](https://user-images.githubusercontent.com/30978328/36506634-2ed9a358-177d-11e8-8396-1b80e3066557.png)

**Comment by astridx** [comment]
I just tested it in the main repo (http://github.com/joomla/joomla-cms/). The problem occurs there, too. So it is not a problem of this repo.
So it is a problem of my installation. @Anu1601CS Can you post your system information please?

**Comment by anuragteapot** [comment]
@astridx Sure

![screenshot from 2018-02-22 03-11-23](https://user-images.githubusercontent.com/30978328/36506938-1b3273d8-177e-11e8-86ea-01a9b5a0136b.png)

I think ,if you are  getting issue with this, also in main repo you can close this here and open this issue in main repo it should be better.

let this repo only for es6 :)
Thanks

**Comment by astridx** [comment]
@Anu1601CS Thank you.
I close this here.
