### ISSUE TITLE
[Inline scripts] components/**/*.php

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/joomla-es6#53]
- [x] `components/com_config/tmpl/config/default.php`
- [x] `components/com_config/tmpl/modules/default.php`
- [x] `components/com_config/tmpl/templates/default.php`
- [x] `components/com_contact/tmpl/categories/default.php`
- [x] `components/com_content/tmpl/form/edit.php`
- [x] `components/com_mailto/tmpl/mailto/default.php`
- [x] `components/com_newsfeeds/tmpl/categories/default.php`
- [x] `components/com_tags/tmpl/tag/default_items.php`
- [x] `components/com_tags/tmpl/tag/list_items.php`
- [x] `components/com_tags/tmpl/tags/default_items.php`

**Comment by dgrammatiko** [comment]
There's a PR for this: https://github.com/joomla/joomla-cms/pull/19671
For the custom fields part

**Comment by dneukirchen** [comment]
Does anybody know how to access `components/com_config/tmpl/modules/default.php` in frontend?

**Comment by dneukirchen** [comment]
WTF we still have com_mailto???

**Comment by C-Lodder** [comment]
@dneukirchen Login as admin in the frontend and go to edit a module. There's currently a PHP error which needs fixing on the main repo before though
