### ISSUE TITLE
No Switcher when creating a menu

### ISSUE THREAD

**Issue by astridx** [joomla-projects/joomla-es6#85]
### Steps to reproduce the issue
1. Open  Menu | Manage  | Add new Menu

### Expected result
You can create a Menu and choose admin or site

### Actual result
You can create a Menu but the switcher for choosing admin or site is not shown

### Additional comments
This issue is not in the 4.0-dev Branch of the main repo 

![menus add es6 administration 1](https://user-images.githubusercontent.com/9974686/36754580-b56f2484-1c09-11e8-8338-24a5d7a22d2c.png)

**Comment by C-Lodder** [comment]
https://github.com/joomla/40-backend-template/issues/359 and https://github.com/joomla/joomla-cms/pull/19296

**Comment by C-Lodder** [comment]
Awaiting a merge on the open PR

**Comment by astridx** [comment]
Are you sure that this depends on that PR's?  The issue occurs not in the main repo.

**Comment by C-Lodder** [comment]
If you open the console log, you should get a warning about the switcher and there only being 1 checkbox input. The PR fixes that. If that's not the error you see, lease me know what you see in the console
